### ISSUE TITLE
Jinja variable 'keyid' is undefined when running aptly.create_mirrors

### ISSUE THREAD

**Issue by jalmansor** [saltstack-formulas/aptly-formula#39]
Running Salt 2016.11.3 and keep having issues with the `create_mirrors` state failing saying that the Jinja variable `keyid` is undefined. 

This is what my `mirrors` pillar section looks like: 

```yaml
  mirrors:
    datadog:
      url: https://apt.datadoghq.com
      distribution: stable
      components:
        - main
        - 6
      keyid:
        - 382E94DE
      architectures:
        - amd64
    trusty-docker-engine:
      url: https://apt.dockerproject.org/repo
      distribution: ubuntu-trusty
      components:
        - main
      key_url: https://apt.dockerproject.org/gpg
      architectures:
        - amd64
    xenial-docker-engine:
      url: https://apt.dockerproject.org/repo
      distribution: ubuntu-xenial
      components:
        - main
      key_url: https://apt.dockerproject.org/gpg
      architectures:
        - amd64
    trusty-docker-ce:
      url: https://download.docker.com/linux/ubuntu
      distribution: trusty
      components:
        - main
      key_url: https://download.docker.com/linux/ubuntu/gpg
      architectures:
        - amd64
    xenial-docker-ce:
      url: https://download.docker.com/linux/ubuntu
      distribution: xenial
      components:
        - main
      key_url: https://download.docker.com/linux/ubuntu/gpg
      architectures:
        - amd64
    trusty-saltstack-2016_11_3:
      url: http://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2016.11.3/
      distribution: trusty
      components:
        - main
      key_url: http://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2016.11.3/SALTSTACK-GPG-KEY.pub
      architectures:
        - amd64
    xenial-saltstack-2016_11_3:
      url: http://repo.saltstack.com/apt/ubuntu/16.04/amd64/archive/2016.11.3/
      distribution: xenial
      components:
        - main
      key_url: http://repo.saltstack.com/apt/ubuntu/16.04/amd64/archive/2016.11.3/SALTSTACK-GPG-KEY.pub
      architectures:
        - amd64
    trusty:
      url: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/
      distribution: trusty
      components:
        - main
        - restricted
        - universe
        - multiverse
      keyid:
        - 437D05B5
      architectures:
        - amd64
    trusty-updates:
      url: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/
      distribution: trusty-updates
      components:
        - main
        - restricted
        - universe
        - multiverse
      keyid:
        - 437D05B5
      architectures:
        - amd64
    trusty-backports:
      url: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/
      distribution: trusty-backports
      components:
        - main
        - restricted
        - universe
        - multiverse
      keyid:
        - 437D05B5
      architectures:
        - amd64
    trusty-security:
      url: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/
      distribution: trusty-security
      components:
        - main
        - restricted
        - universe
        - multiverse
      keyid:
        - 437D05B5
      architectures:
        - amd64
    xenial:
      url: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/
      distribution: xenial
      components:
        - main
        - restricted
        - universe
        - multiverse
      keyid:
        - C0B21F32
      architectures:
        - amd64
    xenial-updates:
      url: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/
      distribution: xenial-updates
      components:
        - main
        - restricted
        - universe
        - multiverse
      keyid:
        - C0B21F32
      architectures:
        - amd64
    xenial-backports:
      url: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/
      distribution: xenial-backports
      components:
        - main
        - restricted
        - universe
        - multiverse
      keyid:
        - C0B21F32
      architectures:
        - amd64
    xenial-security:
      url: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/
      distribution: xenial-security
      components:
        - main
        - restricted
        - universe
        - multiverse
      keyid:
        - C0B21F32
      architectures:
        - amd64
```

Any assistance would be appreciated
